#Allow players to retrieve the golems by bare hand
barehandRetrieve = true
#Max distance to summon single golem
#Range: 1 ~ 1000
summonDistance = 64
#Max distance to retrieve single golem
#Range: 1 ~ 1000
retrieveDistance = 64
#Max distance to retrieve all golems
#Range: 1 ~ 1000
retrieveRange = 20
#Only owner can pickup
ownerPickupOnly = true
#Max golem activity radius before following player in follow mode
#Range: 1.0 ~ 100.0
startFollowRadius = 10.0
#Max golem activity radius before willing to go back to origin in wander mode
#Range: 1.0 ~ 100.0
stopWanderRadius = 20.0
#Max golem activity radius before being teleported back
#Range: 1.0 ~ 100.0
maxWanderRadius = 30.0
#Speed factor for dog golem when ridden by entities
#Range: 0.0 ~ 2.0
riddenSpeedFactor = 0.8
#Target reset time after no movement, in ticks
#Range: 1 ~ 10000
targetResetTime = 600
#Distance considered as no movement
#Range: 0.0 ~ 10.0
targetResetNoMovementRange = 0.5
#Default slots for large golem
#Range: 0 ~ 100
largeGolemSlot = 4
#Default slots for humanoid golem
#Range: 0 ~ 100
humanoidGolemSlot = 3
#Default slots for dog golem
#Range: 0 ~ 100
dogGolemSlot = 2
#Make mobs aggro to iron golem automatically aggro to modular golems
doEnemyAggro = true
#When enabled, the following features will be disabled when player holds item in hand:
#- give item to golem or take items from golem by right click
#- order dog golem to seat
strictInteract = false

[modifiers]
	#Percentage damage reflection per level of thorn
	#Range: 0.0 ~ 100.0
	thorn = 0.2
	#Percentage damage reduction per level of magic resistance
	#Range: 0.0 ~ 1.0
	magicResistance = 0.2
	#Percentage damage reduction per level of explosion resistance
	#Range: 0.0 ~ 1.0
	explosionResistance = 0.2
	#Damage Cap at max level
	#Range: 0.0 ~ 1.0
	damageCap = 0.1
	#Healing when thunder immune golems are striked
	#Range: 1 ~ 10000
	thunderHeal = 10

["twilight forest compat"]
	#Percentage damage addition per level of fiery
	#Range: 0.0 ~ 100.0
	fiery = 0.5
	#Percentage healing bonus per level of twilight healing
	#Range: 0.0 ~ 100.0
	compatTFHealing = 0.5
	#Percentage damage bonus per level of twilight damage
	#Range: 0.0 ~ 100.0
	compatTFDamage = 0.2
	#Time for the golem to be invincible (in ticks) per level of carminite
	#Range: 1 ~ 100000
	carminiteTime = 20

["create compat"]
	#Damage absorbed per level of coating
	#Range: 0.0 ~ 10000.0
	coating = 1.0
	#Speed boost per level of Mechanical Mobility
	#Range: 0.0 ~ 1.0
	mechSpeed = 0.2
	#Attack boost per level of Mechanical Force
	#Range: 0.0 ~ 1.0
	mechAttack = 0.2
	#Maximum number of fuel item that can be added at the same time
	#Range: 1 ~ 364
	mechMaxFuel = 3

["l2complements compat"]
	#Conduit cooldown
	#Range: 0 ~ 10000
	conduitCooldown = 120
	#Conduit damage
	#Range: 0 ~ 10000
	conduitDamage = 2
	#Conduit modifier boosts attack (percentage) when golem is in water
	#Range: 0.0 ~ 100.0
	conduitBoostAttack = 0.2
	#Conduit modifier boosts armor when golem is in water
	#Range: 0 ~ 100
	conduitBoostArmor = 5
	#Conduit modifier boosts toughness when golem is in water
	#Range: 0 ~ 100
	conduitBoostToughness = 2
	#Conduit modifier boosts speed (percentage) when golem is in water
	#Range: 0.0 ~ 100.0
	conduitBoostSpeed = 0.2
	#Conduit modifier reduce damage taken when golem is in water (multiplicative)
	#Range: 0.0 ~ 100.0
	conduitBoostReduction = 0.2
	#Teleport max radius
	#Range: 1 ~ 32
	teleportRadius = 6
	#Teleport cooldown in ticks for avoiding physical damage
	#Range: 1 ~ 10000
	teleportCooldown = 40
	#Damage bonus for attacking specific type of enemy
	#Range: 0.0 ~ 100.0
	targetDamageBonus = 0.5
	#Pickup range per level for pickup upgrade
	#Range: 1 ~ 16
	basePickupRange = 6
	#Mending Xp Cost per health point
	#Range: 1 ~ 10000
	mendingXpCost = 2

["botania compat"]
	#Mana mending cost per HP
	#Range: 1 ~ 50000
	mendingManaCost = 200
	#Mana mending value per level
	#Range: 0.1 ~ 100.0
	manaMendingVal = 4.0
	#Percentage damage bonus per level of mana boost
	#Range: 0.0 ~ 100.0
	manaBoostingDamage = 0.2
	#Mana boosting cost per level (of 1 hit)
	#Range: 0 ~ 100000
	manaBoostingCost = 500
	#Mana production value per level
	#Range: 0 ~ 100000
	manaProductionVal = 20
	#Damage of magic burst as percentage of attack damage
	#Range: 0.0 ~ 1.0
	manaBurstDamage = 0.25
	#Mana burst cost per level
	#Range: 0 ~ 100000
	manaBurstCost = 2000
	#Probability of summoning a pixie when attacking
	#Range: 0.0 ~ 1.0
	pixieAttackProb = 0.05
	#Probability of summoning a pixie when attacked
	#Range: 0.0 ~ 1.0
	pixiecounterattackProb = 0.25

