# Don't change this! Version used to track needed updates.
version = 0
enabled = true
pvpMode = true
manaCost = 400
minLvl = 20
maxLvl = 16
castXP = 65

[cooldown]
base = 1920
perLevel = -20
percent = 0