# Don't change this! Version used to track needed updates.
version = 0
enabled = true
pvpMode = true
manaCost = 240
minLvl = 24
maxLvl = 11
castXP = 65

[cooldown]
base = 1200
perLevel = 0
percent = 0