# Don't change this! Version used to track needed updates.
version = 0
enabled = true
pvpMode = true
manaCost = 750
minLvl = 22
maxLvl = 7
castXP = 100

[cooldown]
base = 12000
perLevel = 0
percent = 0