# Don't change this! Version used to track needed updates.
version = 0
enabled = true
pvpMode = true
manaCost = 300
minLvl = 20
maxLvl = 11
castXP = 65

[cooldown]
base = 2240
perLevel = -40
percent = 0