# Don't change this! Version used to track needed updates.
version = 0
enabled = true
pvpMode = true
manaCost = 250
minLvl = 24
maxLvl = 10
castXP = 30

[cooldown]
base = 4800
perLevel = -120
percent = 0