# Don't change this! Version used to track needed updates.
version = 0
enabled = true
pvpMode = true
manaCost = 150
minLvl = 11
maxLvl = 13
castXP = 40

[cooldown]
base = 1295
perLevel = -15
percent = 0