
[Enchantato-Loot]
	#If you enable this, the 'DisabledEnchantments' will become 'AllowedEnchantments'
	InvertedMode = false
	DisabledEnchantments = ['x_enchantment:more_loot','x_enchantment:increment_attack_damage']

