#Whether Inventory Generators have side effects or not
doSideEffects = true
#Whether Inventory Generators send energy to items in inventory and curios slots when in charging mode
doSendEnergy = true
#Energy capacity of the inventory culinary generator
#Range: > 0
culinaryGeneratorCapacity = 100000
#Energy capacity of the inventory death generator
#Range: > 0
deathGeneratorCapacity = 100000
#Energy capacity of the inventory end generator
#Range: > 0
endGeneratorCapacity = 100000
#Energy capacity of the inventory explosive generator
#Range: > 0
explosiveGeneratorCapacity = 100000
#Energy capacity of the inventory frosty generator
#Range: > 0
frostyGeneratorCapacity = 100000
#Energy capacity of the inventory furnace generator
#Range: > 0
furnaceGeneratorCapacity = 100000
#Energy capacity of the inventory halitosis generator
#Range: > 0
halitosisGeneratorCapacity = 100000
#Energy capacity of the inventory nether star generator
#Range: > 0
netherStarGeneratorCapacity = 10000000
#Energy capacity of the inventory overclocked generator
#Range: > 0
overclockedGeneratorCapacity = 1000000
#Energy capacity of the inventory pink generator
#Range: > 0
pinkGeneratorCapacity = 10000
#Energy capacity of the inventory potion generator
#Range: > 0
potionGeneratorCapacity = 100000
#Energy capacity of the inventory slimey generator
#Range: > 0
slimeyGeneratorCapacity = 100000
#Energy capacity of the inventory survivalist generator
#Range: > 0
survivalistGeneratorCapacity = 10000
#What the burn time of items should be divided by to calculate their generator burn time for the furnace generator
#Range: 1.0 ~ 1.7976931348623157E308
furnaceGeneratorDivisor = 16.0
#The amount of rf per tick generated by burning items in the furnace generator
#Range: > 0
furnaceGeneratorRfPerTick = 40
#The amount of rf per tick the overclocked generator will compare to the burn time of the fuel. The overclocked generator then sends the smaller of the two as the rf per tick
#Range: > 1
overclockedGeneratorDivisor = 4000
#The amount of rf per tick generated by burning items in the survivalist generator
#Range: > 0
survivalistGeneratorRfPerTick = 5
#The probability that the explosive generator will do it's side effect of exploding the player each tick. Calculated as 1/input
#Range: > 1
explosiveGeneratorSideEffectProbability = 400
#The amount that the overall explosion damage of the explosive generator side effect will be divided by to make it less lethal
#Range: > 1
explosionDamageDivisor = 8
#The duration of the wither effect that the nether star generator gives you
#Range: > 0
witherDuration = 20
#The amplifier of the wither effect that the nether star generator gives you
#Range: > 0
witherAmplifier = 9

