
["Client configs for JITL"]
	#If set to 'true', the camera will be locked to the isometric view.
	"Enable Isometric Camera: " = false
	#If set to 'true', the perspective will be locked for the isometric camera.
	"Lock Isometric Perspective: " = false
	#Determines snap angle of the isometric camera view.
	#Allowed Values: NORTH_EAST, SOUTH_EAST, NORTH_WEST, SOUTH_WEST
	"Isometric Camera Angle: " = "NORTH_WEST"
	#If set to 'true', the JITL main menu theme will be enabled by default. This can also be toggled in the main menu itself by pressing the top-left button if enabled.
	"Enable JITL Menu Screen: " = true
	#If set to 'true', the button that toggles the main menu theme will be visible. If set to 'false', the button will no longer appear on the main menu screen.
	"Enable JITL Menu Screen Toggle Button: " = true
	#Determines if/when living entity's health bar will be rendered
	#Allowed Values: ALWAYS, IN_DEBUG_MODE, NEVER
	"Render health: " = "IN_DEBUG_MODE"
	#Determines the position of the Essence bar in-game. 
	#Allowed Values: OVER_EXPERIENCE_BAR, ABOVE_HUNGER_BAR, LEFT_OF_HOTBAR, RIGHT_OF_HOTBAR, BELOW_CROSSHAIR
	"Essence Bar Position: " = "ABOVE_HUNGER_BAR"
	#The width of any big screenshots you may take. 
	#Range: 128 ~ 7680
	"Width: " = 3840
	#The height of any big screenshots you may take. 
	#Range: 72 ~ 4320
	"Height: " = 2160

