
#Client Configs
[general]
	show_low_mana_warning = true
	render_mob_bar = false
	render_death_stats = true
	render_item_rarity_background = true
	show_durability = true
	render_mob_hp_gui = false
	only_render_mob_looked_at = true
	render_floating_damage = false
	#Range: 0.0 ~ 1.0
	ITEM_RARITY_OPACITY = 0.75
	#Range: 0.0 ~ 10.0
	health_bar_gui_scale = 1.0
	#Allowed Values: BOTTOM_CENTER, OVER_VANILLA, TOP_LEFT
	GUI_POSITION = "BOTTOM_CENTER"
	#Allowed Values: BORDER, FULL
	ITEM_RARITY_BACKGROUND_TYPE = "FULL"
	#Allowed Values: RPG, NONE
	PLAYER_GUI_TYPE = "RPG"
	#Range: 1.0E-6 ~ 1.0
	SKILL_TREE_ZOOM_SPEED = 0.15
	#Range: 0 ~ 1000
	REMOVE_EMPTY_TOOLTIP_LINES_IF_MORE_THAN_X_LINES = 30
	ALIGN_STAT_TOOLTIPS = true
	MODIFY_TOOLTIP_LENGTH = true
	IN_DEPTH_TOOLTIPS_BY_DEFAULT = true

