#Disable wool drops to force the player to get shears.
disableWoolDrops = true
#Reset all skills to 1 when a player dies.
deathSkillReset = false
#Starting cost of upgrading to level 2, in levels.
#Range: 0 ~ 10
startingCost = 2
#Amount of levels added to the cost with each upgrade (use 0 for constant cost).
#Range: 0 ~ 10
costIncrease = 1
#Maximum level each skill can be upgraded to.
#Range: 2 ~ 100
maximumLevel = 32
#List of item and block skill requirements.
#Format: mod:id skill:level
#Valid skills: attack, defence, mining, gathering, farming, building, agility, magic (plus any aliases defined in skillAliases)
skillLocks = ["minecraft:iron_sword attack:5", "minecraft:iron_shovel gathering:5", "minecraft:iron_pickaxe mining:5", "minecraft:iron_axe gathering:5", "minecraft:iron_hoe farming:5", "minecraft:iron_helmet defence:5", "minecraft:iron_chestplate defence:5", "minecraft:iron_leggings defence:5", "minecraft:iron_boots defence:5", "minecraft:diamond_sword attack:15", "minecraft:diamond_shovel gathering:15", "minecraft:diamond_pickaxe mining:15", "minecraft:diamond_axe gathering:15", "minecraft:diamond_hoe farming:15", "minecraft:diamond_helmet defence:15", "minecraft:diamond_chestplate defence:15", "minecraft:diamond_leggings defence:15", "minecraft:diamond_boots defence:15", "minecraft:netherite_sword attack:30", "minecraft:netherite_shovel gathering:30", "minecraft:netherite_pickaxe mining:30", "minecraft:netherite_axe gathering:30", "minecraft:netherite_hoe farming:30", "minecraft:netherite_helmet defence:30", "minecraft:netherite_chestplate defence:30", "minecraft:netherite_leggings defence:30", "minecraft:netherite_boots defence:30", "minecraft:fishing_rod gathering:5", "minecraft:shears gathering:5", "minecraft:lead farming:5", "minecraft:bow attack:5 agility:3", "minecraft:turtle_helmet defence:10", "minecraft:shield defence:5", "minecraft:crossbow attack:5 agility:5", "minecraft:trident attack:15 agility:10", "minecraft:golden_apple magic:5", "minecraft:enchanted_golden_apple magic:10", "minecraft:ender_pearl magic:5", "minecraft:ender_eye magic:10", "minecraft:piston building:5", "minecraft:sticky_piston building:10", "minecraft:tnt building:5", "minecraft:ender_chest magic:15", "minecraft:enchanting_table magic:10", "minecraft:anvil building:5", "minecraft:chipped_anvil building:5", "minecraft:damaged_anvil building:5", "minecraft:smithing_table building:10", "minecraft:end_crystal magic:20", "minecraft:boat agility:5", "minecraft:minecart agility:10", "minecraft:elytra agility:20", "minecraft:horse agility:10", "minecraft:donkey agility:10", "minecraft:mule agility:10", "minecraft:strider agility:15"]
#List of requirements to craft items.
#Format: mod:id skill:level
#Valid skills: attack, defence, mining, gathering, farming, building, agility, magic (plus any aliases defined in skillAliases)
craftSkillLocks = []
#List of requirements to attack entities.
#Format: mod:id skill:level
#Valid skills: attack, defence, mining, gathering, farming, building, agility, magic (plus any aliases defined in skillAliases)
attackSkillLocks = []
#List of substitutions to preform in names in skill lock lists.
#Useful if you're using a resource pack to change the names of skills, this config doesn't effect gameplay, just accepted values in other configs so its easier to think about
#Format: key=value
#Valid values: attack, defence, mining, gathering, farming, building, agility, magic
skillAliases = ["defense=defence"]

