#Enables hardcore mode: all bosses will have x10 hp, x2 damage, 100 armor, Shields and Over Shield, Healing, damage absorption 90%
hardcore = true
#Hardcore mode Hp scale
#Range: 1 ~ 2100000000
bossHP = 1
#Hardcore mode attack scale
#Range: 1 ~ 2100000000
bossAttack = 1
#Hardcore mode armor and armor toughness
#Range: 1 ~ 2100000000
armorHardcore = 50
#Hardcore mode damage absorb percent
#Range: 0.0 ~ 1.0
absorbHardcore = 0.3
#Hardcore mode Shield from hp percent 1 is 100%
#Range: 0.1 ~ 2.1E9
shieldHardcore = 1.0
#Hardcore mode Over Shield from hp percent
#Range: 0.1 ~ 2.1E9
overShieldHardcore = 1.0
#Hardcore mode Heal percent from max hp
#Range: 0.0 ~ 2.1E9
healPercent = 0.001
#Challenge cooldown in hours
#Range: 0 ~ 2100000000
cooldown = 8
#How many % of stellar chance will you get on failure
#Range: 0 ~ 100
stellarChanceIncrease = 10
#Base Martyr's Habergeon(armor) value
#Range: > 0
armorAbsorbBase = 40
#Martyr's Habergeon absorption increase %. 1 is 100%, 0.1 is 10%.
#Range: 0.0 ~ 1.0
armorAbsorbPercent = 1.0
#Borders for Anomaly's Ultimate teleportation. Leave at 0 for world's max border.
#Range: > 0
anomalyBorder = 0
#Chance for Atlas to gain Gravity. 1 is 100%, 0.2 is 20%.
#Range: 0.0 ~ 1.0
atlasChance = 0.2
#Level limit for stellar Catalyst
#Range: 0 ~ 255
catalystLvlLimit = 255
#How many debuffs can Catalyst absorb.
#Range: > 0
catalystDeffence = 5
#How many speed will Cat Ears give.
#Range: 0.0 ~ 10.0
catSpeed = 1.0
#Cap for Cat Ears evasion.
#Range: 0 ~ 100
catEvadeCap = 69
#Damage cap for Chaos Core
#Range: > 0
chaosDamageCap = 2147483647
#Chance for Chaos Core reflexion or damage change. 1 is 100%, 0.1 is 10%.
#Range: 0.0 ~ 1.0
chaosChance = 0.1
#How many % from enemy's health will crown give upon kill
#Range: > 0
crownShield = 10
#Chance for Devourer's Ultimate per 1 kill. 1 is 100%, 0.001 is 0.1%
#Range: 0.0 ~ 100.0
devourerChance = 0.001
#Multiplier for Shield that will Flower give by Ultimate.
#Range: 0.0 ~ 2.147483647E9
flowerShield = 1.0
#Killer Queens' Special explosion damage resistance shred
#Range: 0.0 ~ 2.147483647E9
killerRes = 70.0
#Maximum value of Cursed Mark Madness stacks
#Range: > 0
markMaximum = 10
#Heal debt of stellar Cursed Mark Ultimate in max health %
#Range: > 0
markHealDebt = 2000
#Mask of Demon's Special hp consumption value in max health %
#Range: > 0
maskRotAmount = 10
#Chance for Midas getting luck from Ultimate per 1 gold nugget.
#Range: 0.0 ~ 1.0
midasChance = 1.0E-4
#Prism loot chance multiplier
#Range: 0.0 ~ 2.147483647E9
prismChance = 1.0
#Soul Blighter's Ultimate catch chance multiplier
#Range: 0.0 ~ 2.147483647E9
soulBlighterChance = 1.0
#Soul Blighter Over Shield heal multiplier
#Range: 0.0 ~ 2.147483647E9
soulBlighterHeal = 1.0
#Trigon Over Shield heal multiplier
#Range: 0.0 ~ 2.147483647E9
trigonHeal = 1.0
#Sweet Donut max Saturation stacks.
#Range: > 0
donutMaxSaturation = 400
#Base heal bonus of Sweet Donut.
#Range: > 0
donutHealBonus = 40
#How many Shield % will Ball Lightning reduce
#Range: 0.01 ~ 1.0
ballShield = 0.1
#Hardcore mode Shield from hp percent 1 is 100%
#Range: 0.01 ~ 1.0
ballOverShield = 0.2
#Amount of Chaos Core reflection hits from Special
#Range: > 1
chaosCharges = 20
#Devourer cooldown time between rotting hits. 1000 is 1 sec
#Range: 1 ~ 9223372036854775807
devourerCdTime = 200
#Amount of stats per Curse for Mark's Overdrive
#Range: > 1
markBonus = 10
#How many hits can cause Soul Rotting from Devourer
#Range: 0 ~ 2100000000
devourer = 30
#How many ticks must pass before Black Hole hits
#Range: 0 ~ 2100000000
blackhole = 4
#Should anomaly teleport only living entities
anomaly = false
#Minutes before Chaos Core challenge reset
#Range: 1 ~ 2100000000
chaostime = 15
#Chance for Refresher after completing Stellar challenge. 1 is 100%, 0.5 is 50%.
#Range: 0.0 ~ 1.0
refresherChance = 0.5
#This is the number on how many challenge 1 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce1 = 0
#This is the number on how many challenge 2 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce2 = 0
#This is the number on how many challenge 3 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce3 = 0
#This is the number on how many challenge 4 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce4 = 0
#This is the number on how many challenge 5 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce5 = 0
#This is the number on how many challenge 6 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce6 = 0
#This is the number on how many challenge 7 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce7 = 0
#This is the number on how many challenge 8 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce8 = 0
#This is the number on how many challenge 9 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce9 = 0
#This is the number on how many challenge 10 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce10 = 0
#This is the number on how many challenge 11 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce11 = 0
#This is the number on how many challenge 12 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce12 = 0
#This is the number on how many challenge 13 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce13 = 0
#This is the number on how many challenge 14 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce14 = 0
#This is the number on how many challenge 15 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce15 = 0
#This is the number on how many challenge 16 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce16 = 0
#This is the number on how many challenge 17 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce17 = 0
#This is the number on how many challenge 18 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce18 = 0
#This is the number on how many challenge 19 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce19 = 0
#This is the number on how many challenge 20 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce20 = 0
#additional bosses: 
bosses = "hullbreaker,tremorzilla,nucleeper, luxtructosaurus,atlatitan,forsaken,ignited_revenant,void_worm"
#repairObjectsId: 
repairObjects = "mending,repair,unbreak,restore,heal,ingot"
#repairBlackListId: 
repairBlackList = ""
#Reduction of maximum amount needed for Vortex
#Range: > 0
vortexReduction = 0
#Enables Easter event
easter = false
#Nightmare Bosses boxes chance 0.5 is 50%
#Range: 0.0 ~ 1.0
nightmareBoxChance = 0.5
#Nightmare Bosses Refresher chance 0.1 is 10%
#Range: 0.0 ~ 1.0
nightmareRefresherChance = 0.1
#Nightmare Bosses max fragments
#Range: 1 ~ 2100000000
nightmareFrags = 26
#Nightmare Bosses min fragments
#Range: 1 ~ 2100000000
nightmareFragsMin = 13
#Nightmare Bosses max loot multiplier
#Range: 1 ~ 2100000000
nightmareLoot = 20
#Nightmare Bosses min loot multiplier
#Range: 1 ~ 2100000000
nightmareLootMin = 10
#Nightmare Bosses max boxes
#Range: 1 ~ 2100000000
nightmareBoxes = 8
#Nightmare Bosses min boxes
#Range: 1 ~ 2100000000
nightmareBoxesMin = 4
#This is the number on how many challenge 21 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce21 = 0
#This is the number on how many challenge 22 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce22 = 0
#This is the number on how many challenge 23 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce23 = 0
#This is the number on how many challenge 24 maximum progress will be reduced
#Range: -2100000000 ~ 2100000000
challengeReduce24 = 0
#Additional chance for Easter Egg 10 is 10%
#Range: > 0
easterChance = 0
#fishObjects: 
fishObjects = "fish,shell,pearl,boot,treasure,sunken,drown,lure,prismarin,water,ocean,coral,shark,whale,manta,rain,abyss,deep,sea,pirate,ship,bottle"

