# Don't change this! Version used to track needed updates.
version = 0

[vanilla]
enableDesertWorkshops = true
desertWorkshopWeight = 2
enablePlainsWorkshops = true
plainsWorkshopWeight = 3
enableSavannaWorkshops = true
savannaWorkshopWeight = 3
enableSnowyWorkshops = true
snowyWorkshopWeight = 2
enableTaigaWorkshops = true
taigaWorkshopWeight = 3

[ctov]
enableCtovWorkshops = true
beachWorkshopWeight = 4
darkForestWorkshopWeight = 4
jungleWorkshopWeight = 4
jungleTreeWorkshopWeight = 4
mesaWorkshopWeight = 4
mesaFortifiedWorkshopWeight = 4
mountainWorkshopWeight = 4
mountainAlpineWorkshopWeight = 4
mushroomWorkshopWeight = 4
swampWorkshopWeight = 4
swampFortifiedWorkshopWeight = 4

[rs]
enableRsWorkshops = true
badlandsWorkshopWeight = 2
birchWorkshopWeight = 2
darkForestWorkshopWeight = 2
giantTaigaWorkshopWeight = 1
jungleWorkshopWeight = 2
mountainsWorkshopWeight = 2
mushroomsWorkshopWeight = 2
oakWorkshopWeight = 2
swampWorkshopWeight = 2
crimsonWorkshopWeight = 2
warpedWorkshopWeight = 2

[sky]
enableSkyWorkshops = true
skyWorkshopWeight = 40