# Don't change this! Version used to track needed updates.
version = 0
enableBurnout = true
draconicVisionRange = 5

[enabledAugments]
"amethyst_imbuement:angelic" = true
"amethyst_imbuement:bulwark" = true
"amethyst_imbuement:crystalline" = true
"amethyst_imbuement:draconic_vision" = true
"amethyst_imbuement:escape" = true
"amethyst_imbuement:feline" = true
"amethyst_imbuement:friendly" = true
"amethyst_imbuement:guardian" = true
"amethyst_imbuement:hasting" = true
"amethyst_imbuement:headhunter" = true
"amethyst_imbuement:healthy" = true
"amethyst_imbuement:illuminating" = true
"amethyst_imbuement:immunity" = true
"amethyst_imbuement:invisibility" = true
"amethyst_imbuement:leaping" = true
"amethyst_imbuement:lightfooted" = true
"amethyst_imbuement:lucky" = true
"amethyst_imbuement:moonlit" = true
"amethyst_imbuement:resilience" = true
"amethyst_imbuement:shielding" = true
"amethyst_imbuement:slimy" = true
"amethyst_imbuement:soulbinding" = true
"amethyst_imbuement:soul_of_the_conduit" = true
"amethyst_imbuement:spectral_vision" = true
"amethyst_imbuement:spiked" = true
"amethyst_imbuement:strength" = true
"amethyst_imbuement:striding" = true
"amethyst_imbuement:suntouched" = true
"amethyst_imbuement:swiftness" = true
"amethyst_imbuement:undying" = true
"amethyst_imbuement:beast_master" = true
"amethyst_imbuement:beast_magnet" = true